/* Handling Errors in Chains (`.catch()`)

`catch()` is used to handle error that occur anywhere in the
Promise chain.  When a Promise in the chain is rejected,
constrol immediately jumps to the nearest `catch` handler. */

